package com.sit.repo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.sit.entity.ContactDetailsEntity;

/**
 * this is for handling persistance operations
 * @author SATYASACHI
 *
 */

@Repository
public interface ContactDetailsRepository extends JpaRepository<ContactDetailsEntity, Integer> {

	        //implementation  will be provided in the proxy class generated by spring data 
	        //to perform curd operations
}
