server:
  port: 9696
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
   
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
